---
- block:
  - name: "Adding local.conf"
    template:
      src: ../templates/local.conf.j2
      dest: '{{ STACK_DIR }}/devstack/local.conf'

  - name: "Adding local.sh"
    copy:
      src: ../files/local.sh
      dest: '{{ STACK_DIR }}/devstack/local.sh'
      mode: u=rwx,g=r,o=r


  - name: "Running stack.sh. Check stack.log in remote host for more details"
    shell: ./stack.sh >> stack.log 2>&1
    args:
      chdir: "{{ STACK_DIR }}/devstack"

  become: true
  become_user: stack

- name: "templating net_config script to make controller persistent after reboot"
  template:
    src: ../templates/net_config.sh.j2
    dest: /home/{{ ansible_user }}/net_config.sh
    mode: '755'
  tags: persistent_reboot

- name: "set net_config to run at boot using crontab reboot"
  cron:
    name: "net_config cron reboot"
    special_time: reboot
    job: "/home/{{ ansible_user }}/net_config.sh"
  become: true
  tags: persistent_reboot
