---
- block:
  - name: "Ensure python3, python3-pip and virtualenv are available"
    apt:
      # we still need python2 and pip to prevent error
      # https://github.com/ansible/ansible/issues/47361
      name: ['python', 'python-pip', 'python3', 'python3-pip', 'virtualenv']
      state: present
    become: true

  - name: "clone ni_mano"
    git:
      repo: 'https://github.com/dpnm-ni/ni-mano'
      dest: "/home/{{ ansible_user }}/ni_mano"

  - name: "install requirements.txt for {{ SERVICE_MODULE }}"
    pip:
      virtualenv: /home/{{ ansible_user }}/ni_mano/.env
      virtualenv_python: python3
      chdir: /home/{{ ansible_user }}/ni_mano/{{ SERVICE_MODULE }}
      requirements: requirements.txt
      # executable: pip3

  - name: "config {{ SERVICE_MODULE }}"
    template:
      src: ../templates/{{ SERVICE_MODULE }}.yaml.j2
      dest: /home/{{ ansible_user }}/ni_mano/{{ SERVICE_MODULE }}/config/config.yaml
      mode: 0644

  - name: "config {{ SERVICE_MODULE }} as systemd service"
    template:
      src: ../templates/ni@service.j2
      dest: /etc/systemd/system/ni@{{ SERVICE_MODULE }}.service
      mode: 0644
    become: true

  - name: "start {{ SERVICE_MODULE }} service"
    systemd:
      name: ni@{{ SERVICE_MODULE }}.service
      state: restarted
      enabled: true
      daemon_reload: yes
    become: true
